import java.util.Scanner;

public class Examples {
    /* this method finds the largest number generated by 5 calls to Math.random() */
    public static double largestRandom() {
        double max = 0.0;
        for (int i = 1; i <= 5; i++) {
            double nextRandom = Math.random();
            if (nextRandom > max) max = nextRandom;
        }
        return max;
    }

    /* this method inputs test scores from the user and prints:- the lowest score- the highest score- the average (mean) score
user input is terminated with input of any negative number
precondition: user will only enter values <= 100 */
    public static void testData() {
        Scanner scanner = new Scanner(System.in);
        int lowest = Integer.MAX_VALUE;
        int highest = Integer.MIN_VALUE;
        double total = 0.0;
        double average;
        int count = 0;
        System.out.println("enter next score: ");
        int userInput = scanner.nextInt();
        while (userInput >= 0) {
            total += userInput;
            count++;
            if (userInput > highest) highest = userInput;
            if (userInput < lowest) lowest = userInput;
            System.out.println("enter next score: ");
            userInput = scanner.nextInt();
        }
        if (count > 0)  average = total / count;
        else average = 0.0;
        System.out.println("lowest score: " + lowest);
        System.out.println("highest score: " + highest);
        System.out.println("average: " + average);
    }

    public static void main(String[] args) {
        double result1 = largestRandom(); // typically around 0.8333... - n / (n + 1)
        System.out.println(result1);

        testData();
    }
}
