import java.util.Scanner;

public class Exercises {
    /*
    find and print the product of the smallest even number and largest
    odd number generated by 25 calls to NumGen.randomNum()
    in the unlikely scenario that all numbers generated are odd,
    or all numbers are even, print 0 */
    public static void printRandomProduct() {
        int smallEven = Integer.MAX_VALUE;
        int largeOdd = Integer.MIN_VALUE;
        for (int i = 1; i <= 25; i++) {
            int num = NumGen.randomNum();
            if (num % 2 == 0) {
                if (num < smallEven) {
                    smallEven = num;
                }
            }
            else {
                if (num > largeOdd) {
                    largeOdd = num;
                }
            }
        }
        int ans = largeOdd * smallEven;
        System.out.println("Product of the smallest even number and largest odd number: " + ans);
    }

    /* this method asks the user to input 10 numbers
  the program counts how many of the numbers are in the range
  [0, 255] and outputs the largest number within that range
  entered so far after every input. The count is output only at the end */
    public static void eightBitBinaryNums() {
        int count = 0;
        int maxNum = Integer.MIN_VALUE;

        Scanner scanner = new Scanner(System.in);
        for (int i = 1; i <= 10; i++) {
            System.out.println("Input number: ");
            int num = scanner.nextInt();
            if (num > maxNum) {
                maxNum = num;
            }
            System.out.println("Current max number: " + maxNum);

            if (maxNum >= 0 && maxNum <= 255) {
                count++;
            }
        }
        System.out.println("Counts of numbers in the range [0, 255]: " + count);
    }

    public static void main(String[] args) {
        /* todo: test data */
        printRandomProduct();

        eightBitBinaryNums();
    }

}
